---
title: "janna's portfolio"
author: "janna"
date: "2023-02-15"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
    theme: cosmo

---


```{r setup, include=FALSE}
knitr::opts_chunk$set( echo = FALSE, message = FALSE, warning = FALSE, results = FALSE)
library(ggplot2)
library(tidyverse)
library(spotifyr)
library(plotly)
library(flexdashboard)
```





```{r corpus, echo=FALSE}

sadgirl <- get_playlist_audio_features(" ", "1aCB5tYDsZoHJLH6wXNd7T")
notsadgirl <- get_playlist_audio_features (" ", "1dj5yWeujg3pPiIMEDakmm")
corpus <-
  bind_rows(
    sadgirl |> mutate(category = "Sad Girl Music"),
    notsadgirl |> mutate(category = "Not Sad Girl Music")
  )





corpus |>                    # Start with awards.
  mutate(
    mode = ifelse(mode == 0, "Minor", "Major")
  ) |>
  ggplot(                     # Set up the plot.
    aes(
      x = valence,
      y = energy,
      size = loudness,
      colour = mode,
      label = track.name
    )
  )+
  geom_point() +              # Scatter plot.
  geom_rug(linewidth = 0.1) + # Add 'fringes' to show data distribution.
  geom_text(                  # Add text labels from above.
    aes(
      x = valence,
      y = energy,
      label = label,
    ),
    data = 
      tibble(
        label = c(" ", " "),
        category = c("Not Sad Girl Music", "Sad Girl Music"),
        valence = c(0.090, 0.123),
        energy = c(0.101, 0.967),
      ),
    colour = "black",         # Override colour (not mode here).
    size = 3,                 # Override size (not loudness here).
    hjust = "left",           # Align left side of label with the point.
    vjust = "bottom",         # Align bottom of label with the point.
    nudge_x = -0.05,          # Nudge the label slightly left.
    nudge_y = 0.02            # Nudge the label slightly up.
  ) +
  facet_wrap(~ category) +    # Separate charts per playlist.
  scale_x_continuous(         # Fine-tune the x axis.
    limits = c(0, 1),
    breaks = c(0, 0.50, 1),   # Use grid-lines for quadrants only.
    minor_breaks = NULL       # Remove 'minor' grid-lines.
  ) +
  scale_y_continuous(         # Fine-tune the y axis in the same way.
    limits = c(0, 1),
    breaks = c(0, 0.50, 1),
    minor_breaks = NULL
  ) +
  scale_colour_brewer(        # Use the Color Brewer to choose a palette.
    type = "qual",            # Qualitative set.
    palette = "Paired"        # Name of the palette is 'Paired'.
  ) +
  scale_size_continuous(      # Fine-tune the sizes of each point.
    trans = "exp",            # Use an exp transformation to emphasise loud.
    guide = "none"            # Remove the legend for size.
  ) +
  theme_light() +             # Use a simpler theme.
  labs(                       # Make the titles nice.
    x = "Valence",
    y = "Energy",
    colour = "Mode",
    label = "Track name"
  )
ggsave("corpus.pdf", plot=last_plot(), width=15, height = 10)
ggplotly(plot=last_plot())

```
